---
- name: Deploy a Simple Docker App
  hosts: all
  tasks:
    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Run the Nginx container
      community.docker.docker_container:
        name: test-nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8585:80"